name: Execute Cypress Tests Using Docker Image
on: [push]

jobs:
  cypress-Tests:
    name: Run on Chrome 97
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install CI
        run: npm ci

      - name: Install cypress and verify
        run: npm install

      - name: Run Cypress Tests
        run: npm run test
        continue-on-error: false
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
